#!/bin/bash
###############################################################################
#
# Script: epel-release
# Date: 2015/01/01
# Version: V1.0
# Author: Dan Huckson
# Purpose: Install epel-release, (Extra Packages for Enterprise Linux) is open source and free community based repository
#                project from Fedora team which provides 100% high quality add-on software packages for Linux distributions.
#
###############################################################################
#
header
[[ $(($ACTION&$REMOVE)) == $REMOVE ]] && { 
		echo;
		yum -y remove $PACKAGE; 
}

[[ $(($ACTION&$INSTALL)) == $INSTALL ]] && { 
	echo;

	yum -y install $PACKAGE; 
	curl -s http://dl.fedoraproject.org/pub/epel/ > data.tmp
	filename=`cat data.tmp | grep -E -o "RPM-GPG-KEY-EPEL-[0-9]" |  tail -1`
	curl -s -O http://dl.fedoraproject.org/pub/epel/$filename
	rpm --import $filename;
	[ -f $filename ] && rm -f data.tmp
	[ -f $filename ] && rm -f $filename

	PROP=$(($PROP|$INSTALLED))
}
footer
