#!/bin/bash
###############################################################################
#
# Script: net-tools
# Purpose: NetTools is a network toolbox. Scanning network tools are present, but also other multipurpose tools 
#           that could be used by system administrators. 
#
###############################################################################
#
header
[[ $(($ACTION&$REMOVE)) == $REMOVE ]] && { 
	yum -y remove $PACKAGE; 
}

[[ $(($ACTION&$INSTALL)) == $INSTALL ]] && { 
	yum -y install $PACKAGE;
}
footer