#!/bin/bash
###############################################################################
#
# Script: system-user
# Purpose: Add the default system user. 
#
###############################################################################
SERVICE=

header
[[ $(($ACTION&$REMOVE)) == $REMOVE ]] && { 
	echo -e "\n${FG_YELLOW}NOTICE: ${FG_GREEN}Removing user (${FG_CYAN}$USER_ID${FG_GREEN}) from system."
	
	[[ `cat /etc/passwd | grep "$USER_ID"` ]] && { 
		userdel -r "$USER_ID";
		[ "$?" == "0" ] && {	
			groupdel $USER_ID;
			echo -e "${FG_WHITE}SUCCESS: ${FG_GREEN}User (${FG_CYAN}$USER_ID${FG_GREEN}), home folder and mail mailbox have been removed.";
		}
	} || { echo -e "\n${FG_YELLOW}WARNING: ${FG_GREEN}User (${FG_CYAN}$USER_ID${FG_GREEN}) does not exsits."; }
}

[[ $(($ACTION&$INSTALL)) == $INSTALL ]] && { 
	echo -e "\n${FG_YELLOW}NOTICE: ${FG_GREEN}Adding user (${FG_CYAN}$USER_ID${FG_GREEN}) to system.";
	
	[[ `cat /etc/passwd | grep "$USER_ID"` ]] && { 
		userdel -r "$USER_ID"; 
		[ "$?" == "0" ] && { [[ `cat /etc/group | grep "$USER_ID"` ]] && { groupdel $USER_ID; } }
	}
	
	useradd -m -c "$USER_NAME" -s /bin/bash -d $USER_DIR "$USER_ID";
	[ "$?" == "0" ] && {
		echo $USER_PW | passwd --stdin "$USER_ID";
		[ "$?" == "0" ] && {
			sed -i "/root:/ c\root:\t\t$USER_ID" /etc/aliases;
			chmod 750 /home/$USER_ID;
			newaliases;
			[ "$?" == "0" ] && { 
				PROP=$(($PROP|$INSTALLED)); 
				echo -e "${FG_WHITE}SUCCESS: ${FG_GREEN}User (${FG_CYAN}$USER_ID${FG_GREEN}) has been added to system users.";
			} || {
				echo -e "${FG_RED}ERROR: ${FG_GREEN}Could not add user (${FG_CYAN}$USER_ID${FG_GREEN}) to system users.";
			}
		}
	}
}
footer