#!/bin/bash
###############################################################################
#
# Script: Constants
# Purpose: Define constants used for script run actions and results.  
#
###############################################################################
#
# File locations.
###############################################################################
RPM=/bin/rpm
YUM=/usr/bin/yum
CHKCONFIG=/sbin/chkconfig
SYSTEMCTL=/usr/bin/systemctl

# Actions
###############################################################################
ACTION=0
REMOVE=$(( 1 << 0 ))
INSTALL=$(( 1 << 1 ))
RESTART=$(( 1 << 2 ))
UPDATE=$(( 1 << 3 ))

# Properties
###############################################################################
PROP=0
INSTALLED=$(( 1 << 0))
ENABLE=$(( 1 << 1 ))
SERVICE_ON=$(( 1 << 2 ))

# Error codes (ERR_CODE)
###############################################################################
ERR_CODE=0
SUCCESS=$(( 1 << 0 ))
ERROR=$(( 1 << 1 ))
WARNING=$(( 1 << 2 ))
REMOVE_FAIL=$(( 1 << 3 ))
INSTALL_FAIL=$(( 1 << 4 ))
NOT_INSTALLED=$(( 1 << 5 ))
ALREADY_INSTALLED=$(( 1 << 6 ))
STOP=$(( 1 << 7 ))
CONTINUE=$(( 1 << 8 ))
ENABLE_FAIL=$(( 1 << 9 ))
DISABLE_FAIL=$(( 1 << 10 ))

# Runtime settings (RUNTIME)
###############################################################################
EXIT_ON_ERROR=true
EXIT_ON_WARNING=
INSTALL_UPDATE=$(( 1 << 2 ))
INSTALL_RESTORE=$(( 1 << 3 ))
INSTALL_DESTRUCTIVE=$(( 1 << 4 ))

RUNTIME=$(($INSTALL_UPDATE))



# Terminal colors, Foreground colors and Background colors
###############################################################################

FG_BLACK="\e[1;30m"
FG_RED="\e[1;31m"
FG_GREEN="\e[1;32m"
FG_YELLOW="\e[1;33m"
FG_BLUE="\e[1;34m"
FG_MAGENTA="\e[1;35m"
FG_CYAN="\e[1;36m"
FG_WHITE="\e[1;37m"

BG_BLACK="\e[1;40m"
BG_RED="\e[1;41m"
BG_GREEN="\e[1;42m"
BG_YELLOW="\e[1;43m"
BG_BLUE="\e[1;44m"
BG_MAGENTA="\e[1;45m"
BG_CYAN="\e[1;46m"
BG_WHITE="\e[1;47m"



FG_LIGHT_BLACK="\e[1;90m"
FG_LIGHT_RED="\e[1;91m"
FG_LIGHT_GREEN="\e[1;92m"
FG_LIGHT_YELLOW="\e[1;93m"
FG_LIGHT_BLUE="\e[1;94m"
FG_LIGHT_MAGENTA="\e[1;95m"
FG_LIGHT_CYAN="\e[1;96m"
FG_LIGHT_WHITE="\e[1;97m"

BG_LIGHT_BLACK="\e[1;100m"
BG_LIGHT_RED="\e[1;101m"
BG_LIGHT_GREEN="\e[1;102m"
BG_LIGHT_YELLOW="\e[1;103m"
BG_LIGHT_BLUE="\e[1;104m"
BG_LIGHT_MAGENTA="\e[1;105m"
BG_LIGHT_CYAN="\e[1;106m"
BG_LIGHT_WHITE="\e[1;107m"

RESET_ALL="\x1b[0m"




