#!/bin/bash
###############################################################################
#
# Script: Constants
# Purpose: Define constants used for script run actions and results.  
#
###############################################################################
#
# File locations.
###############################################################################
RPM=/bin/rpm
YUM=/usr/bin/yum
CHKCONFIG=/sbin/chkconfig
SYSTEMCTL=/usr/bin/systemctl

# Actions
###############################################################################
ACTION=0
REMOVE=$(( 1 << 0 ))
INSTALL=$(( 1 << 1 ))
RESTART=$(( 1 << 2 ))
UPDATE=$(( 1 << 3 ))

# Properties
###############################################################################
PROP=0
INSTALLED=$(( 1 << 0))
ENABLE=$(( 1 << 1 ))
SERVICE_ON=$(( 1 << 2 ))

# Error codes (ERR_CODE)
###############################################################################
ERR_CODE=0
SUCCESS=$(( 1 << 0 ))
ERROR=$(( 1 << 1 ))
WARNING=$(( 1 << 2 ))
REMOVE_FAIL=$(( 1 << 3 ))
INSTALL_FAIL=$(( 1 << 4 ))
NOT_INSTALLED=$(( 1 << 5 ))
ALREADY_INSTALLED=$(( 1 << 6 ))
STOP=$(( 1 << 7 ))
CONTINUE=$(( 1 << 8 ))
ENABLE_FAIL=$(( 1 << 9 ))
DISABLE_FAIL=$(( 1 << 10 ))

# Runtime settings (RUNTIME)
###############################################################################
EXIT_ON_ERROR=true
EXIT_ON_WARNING=
INSTALL_UPDATE=$(( 1 << 2 ))
INSTALL_RESTORE=$(( 1 << 3 ))
INSTALL_DESTRUCTIVE=$(( 1 << 4 ))

RUNTIME=$(($INSTALL_UPDATE))


# Terminal colors, Foreground colors and Background colors
###############################################################################
FG_BLACK="\e[1;30m"
FG_RED="\e[1;31m"
FG_GREEN="\e[1;32m"
FG_YELLOW="\e[1;33m"
FG_BLUE="\e[1;34m"
FG_MAGENTA="\e[1;35m"
FG_CYAN="\e[1;36m"
FG_WHITE="\e[1;37m"

BG_BLACK="\e[1;40m"
BG_RED="\e[1;41m"
BG_GREEN="\e[1;42m"
BG_YELLOW="\e[1;43m"
BG_BLUE="\e[1;44m"
BG_MAGENTA="\e[1;45m"
BG_CYAN="\e[1;46m"
BG_WHITE="\e[1;47m"

RESET_ALL="\e[0m"
RESET_COLORS="\e[39;49m"
#
