#!/bin/bash
###############################################################################
#
# Script: extras
# Purpose: This script sequences a series of scripts to install. 
#
###############################################################################
#
source settings
source constants
source functions;

action=installer
que=(
	"epel-release"
	"fail2ban"
	"mkkeys" 
	"mod_ssl"
	"bind"
	"postfix"
	"dovecot"
	"mailx"
	"proftpd"
	"awstats"
	"webmin"
	"phpmyadmin"
	"wordpress"	
	"ImageMagick"
);
 
[ "$action" == "installer" ] && { action=$1; packages="${que[@]}"; } || { packages="$@"; }

[ "$action" == "install" ] || [ "$action" == "remove" ] && {

	case $action in 
		install)		ACTION=$(($ACTION|$INSTALL)); ;;
		remove)	ACTION=$(($ACTION|$REMOVE)); ;;
	esac

	[ ! -d ../logs ] && mkdir ../logs;
    
	for PACKAGE in $packages; do
		[ "`is_installed queue/$PACKAGE`" == "0" ] && [ ! -f queue/$PACKAGE ] && {
			echo -e "${BG_BLACK}";
			echo -e "\n${FG_RED}================================================================================"
			echo -e "${FG_RED}= ERROR${FG_GREEN}: Could not find srcipt (${FG_CYAN}$PACKAGE${FG_GREEN}).";
			echo -e "${FG_RED}================================================================================${FG_GREEN}\n"
		} || {
			[ "`is_installed queue/$PACKAGE`" == "1" ] && { PROP=$((0|$INSTALLED)); } || { PROP=0; ERR_CODE=0; } 
			source ./queue/$PACKAGE 2> ../logs/$PACKAGE.err | tee ../logs/$PACKAGE.log;
			[ "$ERR_CODE" != "0" ] && { echo -e "Package (${FG_CYAN}$PACKAGE${FG_GREEN}) finished with errors.\n" >> ../logs/packages.err; }
		}
		[ "$(basename $0)" != "installer" ] && break; 
	done
}