#!/bin/bash
###############################################################################
#
# Script: installer
# Purpose: This script sequences a series of scripts to install, it's the driver that cues up and runs each script. 
#
###############################################################################
#
echo $EXTRAS

CONFIG=settings
 
[ ! -f $CONFIG ] && {
	echo -e "\n\e[1;31m================================================================================\e[0m"
	echo -e "\e[1;31m= ERROR\e[0m: Could not find configuration (\e[1;36m$2\e[0m).";
	echo -e "\e[1;31m================================================================================\e[0m\n"
	exit
}

source settings
source constants
source functions;

export PROP=0;
export ACTION;
export PACKAGE;

que=(
	"user" 
	"ntp"
	"network"
	"httpd"
	"mariadb"
	"php"
);

start_time=$(date +%s)

action=$(basename $0)
[ "$action" == "installer" ] && { action=$1; packages="${que[@]}"; } || { packages="$@"; }

[ "$action" == "install" ] || [ "$action" == "remove" ] && {

	case $action in 
		install)		ACTION=$(($ACTION|$INSTALL)); ;;
		remove)	ACTION=$(($ACTION|$REMOVE)); ;;
	esac

	[ ! -d ../logs ] && mkdir ../logs;
    
	[ "$(basename $0)" == "installer" ] && initialise

	for PACKAGE in $packages; do
		[ "`is_installed base/$PACKAGE`" == "0" ] && [ ! -f base/$PACKAGE ] && {
			echo -e "\n\e[1;31m================================================================================\e[0m"
			echo -e "\e[1;31m= ERROR\e[0m: Could not find srcipt (\e[1;36m$PACKAGE\e[0m).";
			echo -e "\e[1;31m================================================================================\e[0m\n"
		} || {
			[ "`is_installed base/$PACKAGE`" == "1" ] && { PROP=$((0|$INSTALLED)); } || { PROP=0; ERR_CODE=0; } 
			source ./base/$PACKAGE 2> ../logs/$PACKAGE.err | tee ../logs/$PACKAGE.log;
			[ "$ERR_CODE" != "0" ] && { echo -e "Package (\e[1;36m$PACKAGE\e[0m) finished with errors.\n" >> ../logs/packages.err; }
		}
		[ "$(basename $0)" != "installer" ] && break; 
	done

	# Add in configuration queues should be placed below this line.
	[ -f extras ] && source extras;
	# Add on configuration queues should be placed above this line.

	[ "$(basename $0)" == "installer" ] && finalise
}

[ -f $SCRIPTS ] && rm -rf $SCRIPTS

s=$[$(date +%s) - $start_time]; h=$[$s / 3600]; s=$[$s - $[$h * 3600]]; m=$[$s / 60]; s=$[$s - $[m * 60]]
[ "$h" != '0' ] && hours=" \e[1;33m$h\e[0m hours" || hours=""
[ "$m" != '0' ] && minutes=" \e[1;33m$m\e[0m minutes and" || minutes=""

echo -e "\e[1;34m================================================================================\e[0m"
echo -e "\e[1;34m= \e[0mTotal run time$hours$minutes \e[1;33m$s\e[0m seconds."
echo -e "\e[1;34m================================================================================\e[0m\n\n"
echo 
