#!/bin/bash
###############################################################################
#
# Script: setup
# Purpose: Prevent logging in with ssh, set login message and start installer script.  
#
###############################################################################
#
# Once script starts prevent ssh login until finished.
systemctl stop sshd

export EXTRAS=$1
cd $(dirname $(readlink -f $0))/scripts
source ./settings
#source ~/scripts/settings 

# This gets run if setup not started by install script.
[ "$2" != "1" ] && {
	ans=
	while true; do
		clear
		echo -e
		echo -e "###############################################################################";
		echo -e "#";
		echo -e "#              Slingshot Server Configuration Script";
		echo -e "#";
		echo -e "###############################################################################";
		echo -e "#";
		echo -e "#                        *** PLEASE NOTE ***";
		echo -e "#";
		echo -e "# This script needs to connect to remote servers to download the required,";
		echo -e "# software packages. Failure to connect to these sources will cause the,";
		echo -e "# package install to fail, and any packages that depend on them. ";
		echo -e "#";
		echo -e "# The install log files are availble on the target host ($INET_IP) ~/logs.";
		echo -e "#";
		echo -e "###############################################################################"
		echo -e "\nThis script will configure the remote server ($DOMAIN) at address ($INET_IP).";
		echo -e "\nLocal IP=($LOCAL_IP), Target IP=($INET_IP), Target User=($USER_ID)";
		echo -e
		echo -e " b: Slingshot Base Install";
		echo -e " e: Slingshot Base Install + Extras";
		echo -e " q: Quit";
		echo -e 
		echo -n "Enter choice (b/e/q): ";
		read ans;
		case "$ans" in
			b) break; ;;
			e) break; ;;
			q) echo; exit ;;
		esac
	done;

	echo -e  "\n###############################################################################"
}


sed -i "/^#Banner/ c\Banner /etc/issue.net" /etc/ssh/sshd_config

# This rule limits one connection to the SSH port from one IP address per minute
iptables -I INPUT -m hashlimit -m tcp -p tcp --dport 22 --hashlimit 1/min --hashlimit-mode srcip --hashlimit-name ssh -m state --state NEW -j ACCEPT

cat > /etc/issue.net << EOF  


   **************************************************************************************************
   *                                        *** ALERT! ***                                          *
   *                             You are entering into a secured area!                              *
   *                    Your IP Address, Login Time and User Name are Recored.                      *
   *                                                                                                *
   *  This server is restricted to authorized users only. All activities on this system are logged. *
   *   Unauthorized access will be fully investigated and reported to the appropriate authorities.  *
   *                                                                                                *
   **************************************************************************************************


EOF

getent passwd ntp > /dev/null 2&>1
[ $? -eq 0 ] && userdel ntp
echo -e "\n { $USER@$INET_IP }\n"

./installer install
rval=$?

# All done allow ssh logins again.
systemctl start sshd

exit $rval

