#!/bin/bash
###############################################################################
#
# Script: template
# Purpose: A simple template to be used as a starting point for new modules.
#
###############################################################################
#
SERVICE=
header
[[ $(($ACTION&$REMOVE)) == $REMOVE ]] && { 
	yum -y remove $PACKAGE; 
}

[[ $(($ACTION&$INSTALL)) == $INSTALL ]] && { 
	yum -y install $PACKAGE;
}
footer